### ISSUE TITLE
添加两个switch后会报错，然后打不开preview。

### ISSUE THREAD

**Issue by OnlY0226** [vform666/variant-form3-vite#31]
vendor.7d1b3365.js:4 TypeError: Cannot read properties of undefined (reading 'validateField')
    at main.26afb569.js:1:168741
    at main.26afb569.js:1:55698
    at Proxy.forEach (<anonymous>)
    at Proxy.emit$ (main.26afb569.js:1:55686)
    at Proxy.dispatch (main.26afb569.js:1:56132)
    at Proxy.handleChangeEvent (main.26afb569.js:1:69630)
    at Ur (vendor.7d1b3365.js:4:656)
    at er (vendor.7d1b3365.js:4:735)
    at tE (vendor.7d1b3365.js:4:3200)
    at setup (vendor.7d1b3365.js:144:82525)

**Comment by OnlY0226** [comment]
也许是初始值为null的缘故，把初始值默认为true后可以了，或者在配置把默认值null改为false。
